{"uid":"a9211d396efadb63","name":"test_07_scrolling_operations[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_07_scrolling_operations","historyId":"4f6e6ba29e990f6947fcc21bf32a6ee8","time":{"start":1761243552851,"stop":1761243552851,"duration":0},"description":"Test scrolling operations.","descriptionHtml":"<p>Test scrolling operations.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x564ad10f1fba <unknown>\n#1 0x564ad0b766d0 <unknown>\n#2 0x564ad0bfae12 <unknown>\n#3 0x564ad0bf9f9e <unknown>\n#4 0x564ad0bfbb72 <unknown>\n#5 0x564ad0bfb946 <unknown>\n#6 0x564ad0bedc03 <unknown>\n#7 0x564ad0bba7a8 <unknown>\n#8 0x564ad0bbb421 <unknown>\n#9 0x564ad10b6b28 <unknown>\n#10 0x564ad10ba87f <unknown>\n#11 0x564ad109ec49 <unknown>\n#12 0x564ad10bb405 <unknown>\n#13 0x564ad10844ff <unknown>\n#14 0x564ad10df258 <unknown>\n#15 0x564ad10df432 <unknown>\n#16 0x564ad10f0fa3 <unknown>\n#17 0x7fb07ae9caa4 <unknown>\n#18 0x7fb07af29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56200d678fba <unknown>\nE   #1 0x56200d0fd6d0 <unknown>\nE   #2 0x56200d181e12 <unknown>\nE   #3 0x56200d180f9e <unknown>\nE   #4 0x56200d182b72 <unknown>\nE   #5 0x56200d182946 <unknown>\nE   #6 0x56200d174c03 <unknown>\nE   #7 0x56200d1417a8 <unknown>\nE   #8 0x56200d142421 <unknown>\nE   #9 0x56200d63db28 <unknown>\nE   #10 0x56200d64187f <unknown>\nE   #11 0x56200d625c49 <unknown>\nE   #12 0x56200d642405 <unknown>\nE   #13 0x56200d60b4ff <unknown>\nE   #14 0x56200d666258 <unknown>\nE   #15 0x56200d666432 <unknown>\nE   #16 0x56200d677fa3 <unknown>\nE   #17 0x7f322f49caa4 <unknown>\nE   #18 0x7f322f529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564ad10f1fba <unknown>\nE   #1 0x564ad0b766d0 <unknown>\nE   #2 0x564ad0bfae12 <unknown>\nE   #3 0x564ad0bf9f9e <unknown>\nE   #4 0x564ad0bfbb72 <unknown>\nE   #5 0x564ad0bfb946 <unknown>\nE   #6 0x564ad0bedc03 <unknown>\nE   #7 0x564ad0bba7a8 <unknown>\nE   #8 0x564ad0bbb421 <unknown>\nE   #9 0x564ad10b6b28 <unknown>\nE   #10 0x564ad10ba87f <unknown>\nE   #11 0x564ad109ec49 <unknown>\nE   #12 0x564ad10bb405 <unknown>\nE   #13 0x564ad10844ff <unknown>\nE   #14 0x564ad10df258 <unknown>\nE   #15 0x564ad10df432 <unknown>\nE   #16 0x564ad10f0fa3 <unknown>\nE   #17 0x7fb07ae9caa4 <unknown>\nE   #18 0x7fb07af29c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551416,"duration":214},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243552853,"stop":1761243553979,"duration":1126},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x564ad10f1fba <unknown>\n#1 0x564ad0b766d0 <unknown>\n#2 0x564ad0bfae12 <unknown>\n#3 0x564ad0bf9f9e <unknown>\n#4 0x564ad0bfbb72 <unknown>\n#5 0x564ad0bfb946 <unknown>\n#6 0x564ad0bedc03 <unknown>\n#7 0x564ad0bba7a8 <unknown>\n#8 0x564ad0bbb421 <unknown>\n#9 0x564ad10b6b28 <unknown>\n#10 0x564ad10ba87f <unknown>\n#11 0x564ad109ec49 <unknown>\n#12 0x564ad10bb405 <unknown>\n#13 0x564ad10844ff <unknown>\n#14 0x564ad10df258 <unknown>\n#15 0x564ad10df432 <unknown>\n#16 0x564ad10f0fa3 <unknown>\n#17 0x7fb07ae9caa4 <unknown>\n#18 0x7fb07af29c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"Test scrolling operations.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x564ad10f1fba <unknown>\n#1 0x564ad0b766d0 <unknown>\n#2 0x564ad0bfae12 <unknown>\n#3 0x564ad0bf9f9e <unknown>\n#4 0x564ad0bfbb72 <unknown>\n#5 0x564ad0bfb946 <unknown>\n#6 0x564ad0bedc03 <unknown>\n#7 0x564ad0bba7a8 <unknown>\n#8 0x564ad0bbb421 <unknown>\n#9 0x564ad10b6b28 <unknown>\n#10 0x564ad10ba87f <unknown>\n#11 0x564ad109ec49 <unknown>\n#12 0x564ad10bb405 <unknown>\n#13 0x564ad10844ff <unknown>\n#14 0x564ad10df258 <unknown>\n#15 0x564ad10df432 <unknown>\n#16 0x564ad10f0fa3 <unknown>\n#17 0x7fb07ae9caa4 <unknown>\n#18 0x7fb07af29c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56200d678fba <unknown>\nE   #1 0x56200d0fd6d0 <unknown>\nE   #2 0x56200d181e12 <unknown>\nE   #3 0x56200d180f9e <unknown>\nE   #4 0x56200d182b72 <unknown>\nE   #5 0x56200d182946 <unknown>\nE   #6 0x56200d174c03 <unknown>\nE   #7 0x56200d1417a8 <unknown>\nE   #8 0x56200d142421 <unknown>\nE   #9 0x56200d63db28 <unknown>\nE   #10 0x56200d64187f <unknown>\nE   #11 0x56200d625c49 <unknown>\nE   #12 0x56200d642405 <unknown>\nE   #13 0x56200d60b4ff <unknown>\nE   #14 0x56200d666258 <unknown>\nE   #15 0x56200d666432 <unknown>\nE   #16 0x56200d677fa3 <unknown>\nE   #17 0x7f322f49caa4 <unknown>\nE   #18 0x7f322f529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564ad10f1fba <unknown>\nE   #1 0x564ad0b766d0 <unknown>\nE   #2 0x564ad0bfae12 <unknown>\nE   #3 0x564ad0bf9f9e <unknown>\nE   #4 0x564ad0bfbb72 <unknown>\nE   #5 0x564ad0bfb946 <unknown>\nE   #6 0x564ad0bedc03 <unknown>\nE   #7 0x564ad0bba7a8 <unknown>\nE   #8 0x564ad0bbb421 <unknown>\nE   #9 0x564ad10b6b28 <unknown>\nE   #10 0x564ad10ba87f <unknown>\nE   #11 0x564ad109ec49 <unknown>\nE   #12 0x564ad10bb405 <unknown>\nE   #13 0x564ad10844ff <unknown>\nE   #14 0x564ad10df258 <unknown>\nE   #15 0x564ad10df432 <unknown>\nE   #16 0x564ad10f0fa3 <unknown>\nE   #17 0x7fb07ae9caa4 <unknown>\nE   #18 0x7fb07af29c6c <unknown>","steps":[],"attachments":[{"uid":"d40e0f5e65cf772f","name":"log","source":"d40e0f5e65cf772f.txt","type":"text/plain","size":7699},{"uid":"7bbbbfe2be0da933","name":"stdout","source":"7bbbbfe2be0da933.txt","type":"text/plain","size":702},{"uid":"c189ad2ebc4a01c4","name":"stderr","source":"c189ad2ebc4a01c4.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555434,"stop":1761243555434,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"story","value":"Test Various Scrolling Methods"},{"name":"feature","value":"Scrolling"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3443-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"6b1f9f092fbd0617","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/6b1f9f092fbd0617","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137075,"stop":1761243137075,"duration":0}}]},"tags":[]},"source":"a9211d396efadb63.json","parameterValues":["'edge'"]}