INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1142 ==================================================
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1143 Starting new test on CHROME
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/local/bin/chromedriver` in a child process with pid: 8259
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:loggingPrefs": {"performance": "ALL"}, "goog:chromeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.content_settings.exceptions.automatic_downloads.*.setting": 1}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors", "--disable-web-security", "--allow-running-insecure-content"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:41939
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"140.0.7339.207","chrome":{"chromedriverVersion":"140.0.7339.207 (17230b545fd18b35aad49122e5af97a463bc7a9c-refs/branch-heads/7339@{#2364})","userDataDir":"/tmp/.org.chromium.Chromium.Xfk1nC"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:44081"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"e74d18bc4edb0ac0a633b2de9802527c"}} | headers=HTTPHeaderDict({'Content-Length': '850', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/timeouts {"implicit": 10000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/timeouts {"pageLoad": 60000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/url {"url": "https://www.demoblaze.com"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/url HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1163 Navigated to DemoBlaze website on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2255 Testing radio button selection
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/timeouts {"pageLoad": 30000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/url {"url": "https://demo.seleniumeasy.com/basic-radiobutton-demo.html"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=140.0.7339.207)","stacktrace":"#0 0x55ad1d861fba \u003Cunknown>\n#1 0x55ad1d2e66d0 \u003Cunknown>\n#2 0x55ad1d2dd8f8 \u003Cunknown>\n#3 0x55ad1d2cecb6 \u003Cunknown>\n#4 0x55ad1d2d0a00 \u003Cunknown>\n#5 0x55ad1d2cf05e \u003Cunknown>\n#6 0x55ad1d2ce9dc \u003Cunknown>\n#7 0x55ad1d2ce6b5 \u003Cunknown>\n#8 0x55ad1d2cc53b \u003Cunknown>\n#9 0x55ad1d2ccd1a \u003Cunknown>\n#10 0x55ad1d2e9be9 \u003Cunknown>\n#11 0x55ad1d384715 \u003Cunknown>\n#12 0x55ad1d35de32 \u003Cunknown>\n#13 0x55ad1d383b54 \u003Cunknown>\n#14 0x55ad1d35dc03 \u003Cunknown>\n#15 0x55ad1d32a7a8 \u003Cunknown>\n#16 0x55ad1d32b421 \u003Cunknown>\n#17 0x55ad1d826b28 \u003Cunknown>\n#18 0x55ad1d82a87f \u003Cunknown>\n#19 0x55ad1d80ec49 \u003Cunknown>\n#20 0x55ad1d82b405 \u003Cunknown>\n#21 0x55ad1d7f44ff \u003Cunknown>\n#22 0x55ad1d84f258 \u003Cunknown>\n#23 0x55ad1d84f432 \u003Cunknown>\n#24 0x55ad1d860fa3 \u003Cunknown>\n#25 0x7fd858e9caa4 \u003Cunknown>\n#26 0x7fd858f29c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1081', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2282 Selenium Easy failed: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=140.0.7339.207)
Stacktrace:
#0 0x55ad1d861fba <unknown>
#1 0x55ad1d2e66d0 <unknown>
#2 0x55ad1d2dd8f8 <unknown>
#3 0x55ad1d2cecb6 <unknown>
#4 0x55ad1d2d0a00 <unknown>
#5 0x55ad1d2cf05e <unknown>
#6 0x55ad1d2ce9dc <unknown>
#7 0x55ad1d2ce6b5 <unknown>
#8 0x55ad1d2cc53b <unknown>
#9 0x55ad1d2ccd1a <unknown>
#10 0x55ad1d2e9be9 <unknown>
#11 0x55ad1d384715 <unknown>
#12 0x55ad1d35de32 <unknown>
#13 0x55ad1d383b54 <unknown>
#14 0x55ad1d35dc03 <unknown>
#15 0x55ad1d32a7a8 <unknown>
#16 0x55ad1d32b421 <unknown>
#17 0x55ad1d826b28 <unknown>
#18 0x55ad1d82a87f <unknown>
#19 0x55ad1d80ec49 <unknown>
#20 0x55ad1d82b405 <unknown>
#21 0x55ad1d7f44ff <unknown>
#22 0x55ad1d84f258 <unknown>
#23 0x55ad1d84f432 <unknown>
#24 0x55ad1d860fa3 <unknown>
#25 0x7fd858e9caa4 <unknown>
#26 0x7fd858f29c6c <unknown>

DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/timeouts {"pageLoad": 59000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c/url {"url": "https://demoqa.com/radio-button"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "POST /session/e74d18bc4edb0ac0a633b2de9802527c/url HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=500 | data={"value":{"error":"timeout","message":"timeout: Timed out receiving message from renderer: 58.507\n  (Session info: chrome=140.0.7339.207)","stacktrace":"#0 0x55ad1d861fba \u003Cunknown>\n#1 0x55ad1d2e66d0 \u003Cunknown>\n#2 0x55ad1d2ce9ae \u003Cunknown>\n#3 0x55ad1d2ce6b5 \u003Cunknown>\n#4 0x55ad1d2cc53b \u003Cunknown>\n#5 0x55ad1d2cce8f \u003Cunknown>\n#6 0x55ad1d2db7f3 \u003Cunknown>\n#7 0x55ad1d2f4c5b \u003Cunknown>\n#8 0x55ad1d2fb44b \u003Cunknown>\n#9 0x55ad1d2cd5cd \u003Cunknown>\n#10 0x55ad1d2f4988 \u003Cunknown>\n#11 0x55ad1d383eba \u003Cunknown>\n#12 0x55ad1d35dc03 \u003Cunknown>\n#13 0x55ad1d32a7a8 \u003Cunknown>\n#14 0x55ad1d32b421 \u003Cunknown>\n#15 0x55ad1d826b28 \u003Cunknown>\n#16 0x55ad1d82a87f \u003Cunknown>\n#17 0x55ad1d80ec49 \u003Cunknown>\n#18 0x55ad1d82b405 \u003Cunknown>\n#19 0x55ad1d7f44ff \u003Cunknown>\n#20 0x55ad1d84f258 \u003Cunknown>\n#21 0x55ad1d84f432 \u003Cunknown>\n#22 0x55ad1d860fa3 \u003Cunknown>\n#23 0x7fd858e9caa4 \u003Cunknown>\n#24 0x7fd858f29c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1022', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
WARNING  TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:2313 Demoqa failed: Message: timeout: Timed out receiving message from renderer: 58.507
  (Session info: chrome=140.0.7339.207)
Stacktrace:
#0 0x55ad1d861fba <unknown>
#1 0x55ad1d2e66d0 <unknown>
#2 0x55ad1d2ce9ae <unknown>
#3 0x55ad1d2ce6b5 <unknown>
#4 0x55ad1d2cc53b <unknown>
#5 0x55ad1d2cce8f <unknown>
#6 0x55ad1d2db7f3 <unknown>
#7 0x55ad1d2f4c5b <unknown>
#8 0x55ad1d2fb44b <unknown>
#9 0x55ad1d2cd5cd <unknown>
#10 0x55ad1d2f4988 <unknown>
#11 0x55ad1d383eba <unknown>
#12 0x55ad1d35dc03 <unknown>
#13 0x55ad1d32a7a8 <unknown>
#14 0x55ad1d32b421 <unknown>
#15 0x55ad1d826b28 <unknown>
#16 0x55ad1d82a87f <unknown>
#17 0x55ad1d80ec49 <unknown>
#18 0x55ad1d82b405 <unknown>
#19 0x55ad1d7f44ff <unknown>
#20 0x55ad1d84f258 <unknown>
#21 0x55ad1d84f432 <unknown>
#22 0x55ad1d860fa3 <unknown>
#23 0x7fd858e9caa4 <unknown>
#24 0x7fd858f29c6c <unknown>
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1168 Test completed on chrome
INFO     TestDemoBlazeE2E_chrome:test_demoblaze_e2e.py:1169 ==================================================
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 DELETE http://localhost:41939/session/e74d18bc4edb0ac0a633b2de9802527c {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:41939 "DELETE /session/e74d18bc4edb0ac0a633b2de9802527c HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request